/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ShellAiAdvisorRouteImport } from './routes/_shell.ai-advisor'
import { Route as ShellAssetsRouteImport } from './routes/_shell.assets'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellDocumentsRouteImport } from './routes/_shell.documents'
import { Route as ShellExpensesRouteImport } from './routes/_shell.expenses'
import { Route as ShellGoalsRouteImport } from './routes/_shell.goals'
import { Route as ShellIncomeRouteImport } from './routes/_shell.income'
import { Route as ShellInvestmentsRouteImport } from './routes/_shell.investments'
import { Route as ShellLoansRouteImport } from './routes/_shell.loans'
import { Route as ShellPropertiesRouteImport } from './routes/_shell.properties'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAiAdvisorRoute = ShellAiAdvisorRouteImport.update({
  id: '/ai-advisor',
  path: '/ai-advisor',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAssetsRoute = ShellAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocumentsRoute = ShellDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExpensesRoute = ShellExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => ShellRoute,
} as any)
const ShellGoalsRoute = ShellGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIncomeRoute = ShellIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInvestmentsRoute = ShellInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLoansRoute = ShellLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPropertiesRoute = ShellPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ai-advisor': typeof ShellAiAdvisorRoute
  '/assets': typeof ShellAssetsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/documents': typeof ShellDocumentsRoute
  '/expenses': typeof ShellExpensesRoute
  '/goals': typeof ShellGoalsRoute
  '/income': typeof ShellIncomeRoute
  '/investments': typeof ShellInvestmentsRoute
  '/loans': typeof ShellLoansRoute
  '/properties': typeof ShellPropertiesRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ai-advisor': typeof ShellAiAdvisorRoute
  '/assets': typeof ShellAssetsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/documents': typeof ShellDocumentsRoute
  '/expenses': typeof ShellExpensesRoute
  '/goals': typeof ShellGoalsRoute
  '/income': typeof ShellIncomeRoute
  '/investments': typeof ShellInvestmentsRoute
  '/loans': typeof ShellLoansRoute
  '/properties': typeof ShellPropertiesRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_shell/ai-advisor': typeof ShellAiAdvisorRoute
  '/_shell/assets': typeof ShellAssetsRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/documents': typeof ShellDocumentsRoute
  '/_shell/expenses': typeof ShellExpensesRoute
  '/_shell/goals': typeof ShellGoalsRoute
  '/_shell/income': typeof ShellIncomeRoute
  '/_shell/investments': typeof ShellInvestmentsRoute
  '/_shell/loans': typeof ShellLoansRoute
  '/_shell/properties': typeof ShellPropertiesRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/settings': typeof ShellSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/ai-advisor'
    | '/assets'
    | '/dashboard'
    | '/documents'
    | '/expenses'
    | '/goals'
    | '/income'
    | '/investments'
    | '/loans'
    | '/properties'
    | '/reports'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/ai-advisor'
    | '/assets'
    | '/dashboard'
    | '/documents'
    | '/expenses'
    | '/goals'
    | '/income'
    | '/investments'
    | '/loans'
    | '/properties'
    | '/reports'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/register'
    | '/_shell/ai-advisor'
    | '/_shell/assets'
    | '/_shell/dashboard'
    | '/_shell/documents'
    | '/_shell/expenses'
    | '/_shell/goals'
    | '/_shell/income'
    | '/_shell/investments'
    | '/_shell/loans'
    | '/_shell/properties'
    | '/_shell/reports'
    | '/_shell/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/ai-advisor': {
      id: '/_shell/ai-advisor'
      path: '/ai-advisor'
      fullPath: '/ai-advisor'
      preLoaderRoute: typeof ShellAiAdvisorRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/assets': {
      id: '/_shell/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof ShellAssetsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/documents': {
      id: '/_shell/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof ShellDocumentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/expenses': {
      id: '/_shell/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ShellExpensesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/goals': {
      id: '/_shell/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof ShellGoalsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/income': {
      id: '/_shell/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof ShellIncomeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/investments': {
      id: '/_shell/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof ShellInvestmentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/loans': {
      id: '/_shell/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof ShellLoansRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/properties': {
      id: '/_shell/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof ShellPropertiesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAiAdvisorRoute: typeof ShellAiAdvisorRoute
  ShellAssetsRoute: typeof ShellAssetsRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellDocumentsRoute: typeof ShellDocumentsRoute
  ShellExpensesRoute: typeof ShellExpensesRoute
  ShellGoalsRoute: typeof ShellGoalsRoute
  ShellIncomeRoute: typeof ShellIncomeRoute
  ShellInvestmentsRoute: typeof ShellInvestmentsRoute
  ShellLoansRoute: typeof ShellLoansRoute
  ShellPropertiesRoute: typeof ShellPropertiesRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAiAdvisorRoute: ShellAiAdvisorRoute,
  ShellAssetsRoute: ShellAssetsRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellDocumentsRoute: ShellDocumentsRoute,
  ShellExpensesRoute: ShellExpensesRoute,
  ShellGoalsRoute: ShellGoalsRoute,
  ShellIncomeRoute: ShellIncomeRoute,
  ShellInvestmentsRoute: ShellInvestmentsRoute,
  ShellLoansRoute: ShellLoansRoute,
  ShellPropertiesRoute: ShellPropertiesRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
